export const departments = [
  { value: "", label: "Select" },
  { value: "HR", label: "HR" },
  { value: "IT", label: "IT" },
  { value: "FIN", label: "Finance" },
  { value: "SALES", label: "Sales" },
  { value: "MKT", label: "Marketing" },
  { value: "OPS", label: "Operations" },
  { value: "SUP", label: "Support" },
  { value: "ADM", label: "Admin" },
  { value: "QA", label: "QA" },
  { value: "R&D", label: "R&D" },
];

export const designations = [
  { value: "", label: "Select" },
  { value: "Accountant", label: "Accountant" },
  { value: "Admin Executive", label: "Admin Executive" },
  { value: "Auditor", label: "Auditor" },
  { value: "Backend Developer", label: "Backend Developer" },
  { value: "Business Development Executive (BDE)", label: "Business Development Executive (BDE)", },
  { value: "Business Development Manager (BDM)", label: "Business Development Manager (BDM)", },
  { value: "CEO (Chief Executive Officer)", label: "CEO (Chief Executive Officer)", },
  { value: "CFO (Chief Financial Officer)", label: "CFO (Chief Financial Officer)", },
  { value: "COO (Chief Operating Officer)", label: "COO (Chief Operating Officer)", },
  { value: "CTO (Chief Technology Officer)", label: "CTO (Chief Technology Officer)", },
  { value: "Customer Service Representative", label: "Customer Service Representative", },
  { value: "Data Analyst", label: "Data Analyst" },
  { value: "Data Scientist", label: "Data Scientist" },
  { value: "DevOps Engineer", label: "DevOps Engineer" },
  { value: "Digital Marketing Executive", label: "Digital Marketing Executive", },
  { value: "Director", label: "Director" },
  { value: "Finance Executive", label: "Finance Executive" },
  { value: "Finance Manager", label: "Finance Manager" },
  { value: "Frontend Developer", label: "Frontend Developer" },
  { value: "Full Stack Developer", label: "Full Stack Developer" },
  { value: "General Manager", label: "General Manager" },
  { value: "Graphic Designer", label: "Graphic Designer" },
  { value: "HR Executive", label: "HR Executive" },
  { value: "HR Generalist", label: "HR Generalist" },
  { value: "HR Manager", label: "HR Manager" },
  { value: "Marketing Executive", label: "Marketing Executive" },
  { value: "Office Assistant", label: "Office Assistant" },
  { value: "Office Manager", label: "Office Manager" },
  { value: "Operations Executive", label: "Operations Executive" },
  { value: "Operations Manager", label: "Operations Manager" },
  { value: "Process Coordinator", label: "Process Coordinator" },
  { value: "Product Manager", label: "Product Manager" },
  { value: "Project Manager", label: "Project Manager" },
  { value: "Python Developer", label: "Python Developer" },
  { value: "QA Analyst", label: "QA Analyst" },
  { value: "QA Engineer", label: "QA Engineer" },
  { value: "Recruiter", label: "Recruiter" },
  { value: "Sales Executive", label: "Sales Executive" },
  { value: "Sales Manager", label: "Sales Manager" },
  { value: "SEO Specialist", label: "SEO Specialist" },
  { value: "Social Media Manager", label: "Social Media Manager" },
  { value: "Software Engineer", label: "Software Engineer" },
  { value: "Support Executive", label: "Support Executive" },
  { value: "System Administrator", label: "System Administrator" },
  { value: "Talent Acquisition Specialist", label: "Talent Acquisition Specialist", },
  { value: "Technical Support Engineer", label: "Technical Support Engineer", },
  { value: "UI/UX Designer", label: "UI/UX Designer" },
  ];