# Generated by Django 6.0.2 on 2026-07-22 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pay_month",
                    models.DateField(
                        help_text="Use any date in the month (e.g., 2026-02-01)"
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("is_finalized", models.BooleanField(default=False)),
                (
                    "amt_per_day",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("worked_days", models.IntegerField(default=0)),
                ("leave_taken", models.IntegerField(default=0)),
                (
                    "basic",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "hra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("pf", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "stored_gross",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "stored_total_deductions",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "stored_net_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_history",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-pay_month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "pay_month"),
                        name="unique_employee_month_salary",
                    )
                ],
            },
        ),
    ]
