# Generated by Django 6.0.2 on 2026-07-22 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("", "Select"),
                            ("Accountant", "Accountant"),
                            ("Admin Executive", "Admin Executive"),
                            ("Auditor", "Auditor"),
                            ("Backend Developer", "Backend Developer"),
                            (
                                "Business Development Executive (BDE)",
                                "Business Development Executive (BDE)",
                            ),
                            (
                                "Business Development Manager (BDM)",
                                "Business Development Manager (BDM)",
                            ),
                            (
                                "CEO (Chief Executive Officer)",
                                "CEO (Chief Executive Officer)",
                            ),
                            (
                                "CFO (Chief Financial Officer)",
                                "CFO (Chief Financial Officer)",
                            ),
                            (
                                "COO (Chief Operating Officer)",
                                "COO (Chief Operating Officer)",
                            ),
                            (
                                "CTO (Chief Technology Officer)",
                                "CTO (Chief Technology Officer)",
                            ),
                            (
                                "Customer Service Representative",
                                "Customer Service Representative",
                            ),
                            ("Data Analyst", "Data Analyst"),
                            ("Data Scientist", "Data Scientist"),
                            ("DevOps Engineer", "DevOps Engineer"),
                            (
                                "Digital Marketing Executive",
                                "Digital Marketing Executive",
                            ),
                            ("Director", "Director"),
                            ("Finance Executive", "Finance Executive"),
                            ("Finance Manager", "Finance Manager"),
                            ("Frontend Developer", "Frontend Developer"),
                            ("Full Stack Developer", "Full Stack Developer"),
                            ("General Manager", "General Manager"),
                            ("Graphic Designer", "Graphic Designer"),
                            ("HR Executive", "HR Executive"),
                            ("HR Generalist", "HR Generalist"),
                            ("HR Manager", "HR Manager"),
                            ("Marketing Executive", "Marketing Executive"),
                            ("Office Assistant", "Office Assistant"),
                            ("Office Manager", "Office Manager"),
                            ("Operations Executive", "Operations Executive"),
                            ("Operations Manager", "Operations Manager"),
                            ("Process Coordinator", "Process Coordinator"),
                            ("Product Manager", "Product Manager"),
                            ("Project Manager", "Project Manager"),
                            ("Python Developer", "Python Developer"),
                            ("QA Analyst", "QA Analyst"),
                            ("QA Engineer", "QA Engineer"),
                            ("Recruiter", "Recruiter"),
                            ("Sales Executive", "Sales Executive"),
                            ("Sales Manager", "Sales Manager"),
                            ("SEO Specialist", "SEO Specialist"),
                            ("Social Media Manager", "Social Media Manager"),
                            ("Software Engineer", "Software Engineer"),
                            ("Support Executive", "Support Executive"),
                            ("System Administrator", "System Administrator"),
                            (
                                "Talent Acquisition Specialist",
                                "Talent Acquisition Specialist",
                            ),
                            (
                                "Technical Support Engineer",
                                "Technical Support Engineer",
                            ),
                            ("UI/UX Designer", "UI/UX Designer"),
                        ],
                        default="Select",
                        max_length=120,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("", "Select"),
                            ("HR", "HR"),
                            ("IT", "IT"),
                            ("FIN", "Finance"),
                            ("SALES", "Sales"),
                            ("MKT", "Marketing"),
                            ("OPS", "Operations"),
                            ("SUP", "Support"),
                            ("ADM", "Admin"),
                            ("QA", "QA"),
                            ("R&D", "R&D"),
                        ],
                        default="Select",
                        max_length=20,
                    ),
                ),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="employees/photos/"
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="employees.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
